name: PHPUnit tests

on:
  push:
    branches:
      - main
      - github-actions
      - test
  pull_request:
    branches:
      - main
      - test
  schedule:
    - cron: '0 5 * * 5'
  workflow_dispatch:

jobs:
  github-title:
    name: (php, laravel, DBAL)
    runs-on: ubuntu-latest
    steps:
      - name: Print Legend
        run: echo "This prints the test legend at the top of the Github Actions jobs"
  build-and-test:
    name: Test (p,l,d)
    strategy:
      fail-fast: false
      matrix:
        php: ["7.3", "7.4", "8.0", "8.1", "8.2", "8.3"]
        laravel: [^6.0, ^7.0, ^8.0, ^9.0, ^10.0, ^11.0]
        dbal: [^2.6, ^3.0]
        exclude:
          - php: 7.3
            laravel: ^9.0
          - php: 7.3
            laravel: ^10.0
          - php: 7.3
            laravel: ^11.0
          - php: 7.4
            laravel: ^9.0
          - php: 7.4
            laravel: ^10.0
          - php: 7.4
            laravel: ^11.0
          - php: 8.0
            laravel: ^5.8
          - php: 8.0
            laravel: ^10.0
          - php: 8.0
            laravel: ^11.0
          - php: 8.1
            laravel: ^5.8
          - php: 8.1
            laravel: ^6.0
          - php: 8.1
            laravel: ^7.0
          - php: 8.1
            laravel: ^11.0
          - php: 8.2
            laravel: ^5.8
          - php: 8.2
            laravel: ^6.0
          - php: 8.2
            laravel: ^7.0
          - php: 8.3
            laravel: ^5.8
          - php: 8.3
            laravel: ^6.0
          - php: 8.3
            laravel: ^7.0
          - laravel: ^5.8
            dbal: ^3.0
          - laravel: ^6.0
            dbal: ^3.0
          - laravel: ^7.0
            dbal: ^3.0
          - laravel: ^10.0
            dbal: ^2.6
          - laravel: ^11.0
            dbal: ^2.6
            
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "highest"
          composer-options: "--with laravel/framework:${{ matrix.laravel }} --with doctrine/dbal:${{ matrix.dbal }}"
      - name: Create Database Containers
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 3
          command: pwd;docker compose up -d
      - name: List Database Containers
        run: docker compose ps
      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping --host=127.0.0.1 --port=33067 --silent; do
            sleep 1
          done
      - name: List Database Containers
        run: docker compose ps
      - name: Run PHPUnit Unit Tests
        run: vendor/bin/phpunit -c phpunit.xml.dist

